version: "3.9"
services:
  app:
    image: openvidu/openvidu-call:2.21.0
    restart: on-failure
    ports:
      - "3478:5442"
    environment:
      - SERVER_PORT=5442
      - OPENVIDU_URL=${DOMAIN_OR_PUBLIC_IP}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}